### ISSUE TITLE
[BUG 🐞] User attributes are not loading 

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#100]
### Description

- Only CREATED tab is loading
- CREATED, LIKED, PRIVATE, COMMENTS must start fetching once page loads 

### Screenshots

![Screenshcom android chrome](https://github.com/warmachine028/memories/assets/75939390/f4a0a07a-1ce9-41d7-bda0-575ea501fadc)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by cesardlinx** [comment]
I can work on this @warmachine028
