### ISSUE TITLE
[ FEATURE 💡]  Transparent effect to cards and navbar

### ISSUE THREAD

**Issue by huamanraj** [warmachine028/memories#104]
I want to work on for giving some transparent or glass-like effect in UI for Hacktoberfest 
![Screenshot (89)](https://github.com/warmachine028/memories/assets/113578582/2b4a46f2-59cf-42cd-8874-77a638e2bb7f)

**Comment by warmachine028** [comment]
The UI is already transparent, see the light mode, if you can show some ways on how to improve the dark mode ui, i might assign this issue to you

**Comment by warmachine028** [comment]
And next time use the Feature template for issues like these instead of others

**Comment by warmachine028** [comment]
Closing as not responded
