### ISSUE TITLE
[BUG 🐞] recommended use of Prefer RegExptest() over Stringmatch()

### ISSUE THREAD

**Issue by beneyalraj** [warmachine028/memories#105]
### Description

Performance can be improved by using regexpTest() over Stringmatch()

### Screenshots

<img width="785" alt="Screenshot 2023-10-05 at 11 03 34 PM" src="https://github.com/warmachine028/memories/assets/42829681/9881f61a-88ff-4467-b8c3-8fc4031633b9">

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by ujwalkumar1995** [comment]
Hey @beneyalraj 
I would like to work on this issue. Could you please assign?

**Comment by beneyalraj** [comment]
I've worked on it already and raised this issue to get assigned to it. Sorry, I would open someother new issues which you could contribute to

**Comment by warmachine028** [comment]
@beneyalraj the changes you are making are very minor ones, we both are quite aware of the fact that these are not quality contributions. So why don't you identify some more bugs and solve it under a single issue instead of creating multiple PRs for the same

**Comment by warmachine028** [comment]
I'm assigning you in this issue

**Comment by beneyalraj** [comment]
@warmachine028 thankyou for making it clear. ill try to solve few bugs under a single issue and make the PR.

**Comment by warmachine028** [comment]
Yes keep contributing 🥂
