### ISSUE TITLE
[FEATURE 💡] Enhancements for Light mode  

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#107]
### Description

- During development of the Dark mode, various texts were converted to white color for visibility in both modes properly.
- But some colors fit only the Light mode perfectly. Hence some changes are to be brought back.
- **All of these changes are to be made for Light theme without hampering the existing colors or UI of the Dark theme**
- Your changes should be compatible with all devices, **check responsive properly especially for mobile devices**.
- [ ] Change the Post Upload Form Title color to Black.
- [ ] The post title font should be a bit increased.
- [ ] The Comment Text area has a white background, this must be removed.
- [ ] Bring back the changes in Light theme which existed in [previous Deployment](https://memories-5xye0f5aj-warmachine028.vercel.app) without hampering the dark mode UI.
- Take reference from the old deployment to apply these changes.

### Screenshots

Previous Deployment for Light mode
- ![Screenshot_2023-10-06-00-25-38-236_com android chrome](https://github.com/warmachine028/memories/assets/75939390/1673e8f4-4a2b-4191-8eca-a7426bc8b507)

Current Deployment for Light mode
- ![Screenshot_2023-10-06-00-28-04-523_com android chrome](https://github.com/warmachine028/memories/assets/75939390/cedd3b25-6a9f-4ebb-848d-6ad2af5670d0)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Tholkappiar** [comment]
**Hello Maintainers** ,  
- Can you please provide the main thing info which you wanted to implement in this issue ? 
- `The Comment Text area has a white background, this must be removed.` has to be replaced by what ? 
- Can you please describe what changes to made in the light theme without hampering the dark theme ? 
- And what does this mean  ? `But some colors fit only the Light mode perfectly`

**Comment by warmachine028** [comment]
- Did you see the screenshot I provided below properly?
- Did you go through the UI thoroughly both in current and Previous Deployment?
- Did you take your time and read the check boxes?

**Comment by Tholkappiar** [comment]
_Done
Done
Done_

- Did you mention any color which is not suitable `But some colors fit only the Light mode perfectly` ?
- Did you mention any specific area which has to be updated ? Can i update anything like in the UI ?
- Did you take your time and read my question ?

**Its your job to explain the things for the contribution , right ? then also why did you then add the label as **good first issue** then , for the repo reach  ?**

**Comment by warmachine028** [comment]
- First of all ofcourse it's a good first issue, the changes I asked to do are not too difficult to make for a beginner. I didn't ask you to build up a complete page from the beginning, just make small changes without hampering existing ones are expected from you.
- Previously contributors have devoted great time to make valuable contributions to this project so there's no need for me to do such thing for repo reach, besides there's no such thing as repo reach in my case, I am personally devoting my time to get these people get their hacktoberfest issues accepted after making proper contributions without getting any fame on my side.
- If you don't find this issue on your expertise then you can check out other projects.
- I read your question that's why I stated you to read the issue properly and go through the UI first.
- Regarding the color, we are only using 2 colors for the UI texts Black and White, 
- The text color should be black as previous UI but only for Light mode.
- The PostDetail page is given in the Screenshots so only PostDetails page is to be updated

**Comment by Faisalhs51** [comment]
Basically you want text colors from previous deployment back in the light mode.
Assign this to me.

**Comment by warmachine028** [comment]
> Basically you want text colors from previous deployment back in the light mode. Assign this to me.

Assigned let me know if any query arises, I'll assist you

**Comment by Tholkappiar** [comment]
what is the meaning of `good first issue` - only means that are not difficult ? you have to answer and collaborate the work and should answer the questions which are asked  ! not only means it is not difficult , if your are doing without anything your side , do it properly ! Don't ask question like this https://github.com/warmachine028/memories/issues/107#issuecomment-1750014862 without knowing what the opposite person is doing on the repo !
