### ISSUE TITLE
[FEATURE 💡] Dark Mode for User Profile

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#109]
### Description

+ Add dark mode to user profile
+ Match the appearance of the existing UI

### Screenshots

![Screenshot_2023-10-06-20-57-46-818_com android chrome](https://github.com/warmachine028/memories/assets/75939390/1e92dcec-693f-4ae7-9f9a-21db9e443637)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by waleedkhano** [comment]
Hello, @warmachine028  May I work on this?

**Comment by warmachine028** [comment]
Sure, you can.

**Comment by ShrutiKolla** [comment]
Hello, @warmachine028 Can I please work on this?

**Comment by KhyathiKancharla** [comment]
Hello @warmachine028 , I have done this feature before
Can you please assign me this?

**Comment by warmachine028** [comment]
@ShrutiKolla, @waleedkhano has already made a PR. If he is unable to make the requested changes you will be assigned.
Meanwhile look for other ways to improve this project and make an issue, you'll be assigned to that
