### ISSUE TITLE
[FEATURE 💡] Dark mode for public Profile

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#114]
### Description

- If possible make use of the Classes already present in UserProfile component

## Click here to reach public profile:

+ ![Screenshot_2023-10-10-19-16-50-686_com**_ android chrome-edit](https://github.com/warmachine028/memories/assets/75939390/f3054055-5478-41b8-b2d1-6d8fb9e8a995)

## Public Profile

+ ![Screenshot_2023-10-10-19-17-08-324_com android chrome](https://github.com/warmachine028/memories/assets/75939390/47d241bf-a9af-4eda-8bae-7457350b3888)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Milind-Palaria** [comment]
hey @warmachine028 , can you assign this to me?

**Comment by warmachine028** [comment]
@Milind-Palaria What's the status on this?

**Comment by warmachine028** [comment]
@VinayakVispute Please work in this. Seems like the previous assignee has left this issue to stale

**Comment by VinayakVispute** [comment]
@warmachine028 Ok no problem..... I will make PR tonight

**Comment by warmachine028** [comment]
Sure @VinayakVispute

**Comment by warmachine028** [comment]
@VinayakVispute, please make 2 seperate PR s for the 2 issues

**Comment by warmachine028** [comment]
@VinayakVispute what's the status

**Comment by VinayakVispute** [comment]
@warmachine028 Sorry for delay My exams were going on and dont worry my exams are over today, just give me this as a last chance

**Comment by warmachine028** [comment]
No problems I can understand.

**Comment by VinayakVispute** [comment]
![image](https://github.com/warmachine028/memories/assets/93467074/9554210e-a82c-4993-9358-56488296b9ff)


@warmachine028 You want me to apply here ?

**Comment by warmachine028** [comment]
Yes

**Comment by warmachine028** [comment]
@VinayakVispute what's the status?

**Comment by VinayakVispute** [comment]
@warmachine028 Apologies for the delay; I will finalize this tonight.

**Comment by warmachine028** [comment]
@VinayakVispute what's the status on this issue?

**Comment by VinayakVispute** [comment]
I am making PR Now
