### ISSUE TITLE
[FEATURE 💡] Tag Sugessions

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#115]
### Description

- Fetch all tags from the database using a method. 
- Then display tag suggestions to select from to the user using AutoComplete.
- This feature can be added in Forms so that users don't create duplicate tags and use existing ones.
- If you are unable to connect to database because u don't have mongoDB string please do it using some mock tags stored in an array in frontEnd itself.
- See this [page](https://mui.com/material-ui/react-autocomplete/) for the Autocomplete component

### Screenshots

![image](https://github.com/warmachine028/memories/assets/75939390/5022c6ea-9e59-4ed1-aac6-ff70e0f1655e)

![download](https://github.com/warmachine028/memories/assets/75939390/675a2964-0e43-4e74-8fc1-ab66f3de5367)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by JayeshYadav99** [comment]
@warmachine028 ,I want to work on this issue

**Comment by warmachine028** [comment]
Assigning you
