### ISSUE TITLE
[BUG 🐞] Found variable shadowing & unreachable code

### ISSUE THREAD

**Issue by beneyalraj** [warmachine028/memories#116]
### Description

Found variable shadowing in 2 files and an unreachable code line in 1 file

### Screenshots

![Screenshot 2023-10-13 at 12 39 15 AM](https://github.com/warmachine028/memories/assets/42829681/84ce89d6-8d5e-491a-8354-a3fdbaf909cf)
<img width="784" alt="Screenshot 2023-10-13 at 12 40 28 AM" src="https://github.com/warmachine028/memories/assets/42829681/c8e69948-a9ce-41c9-9f4c-4e121fa6016c">

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by beneyalraj** [comment]
i would like to work on this minor fix

**Comment by warmachine028** [comment]
Work on it
