### ISSUE TITLE
[BUG 🐞] Implement Loading Component to Enhance Page Refresh Experience ⏳🔁

### ISSUE THREAD

**Issue by VinayakVispute** [warmachine028/memories#118]
## Issue Description

When refreshing the page, a loading animation appears for the posts, which is expected behavior. However, there is an issue with the pagination. Initially, the pagination shows only "1" as the page number, and then it suddenly updates to show the actual page numbers. To address this issue and provide a more seamless user experience, it is necessary to implement a loading component that can handle these conditions:

- Display a loading animation for posts while the page is being refreshed.
- Show an accurate page number on the pagination from the beginning.
- Ensure that the loading animation transitions smoothly to reveal the actual content when it's ready, without abrupt updates or changes.

### Screenshots

[Issue.webm](https://github.com/warmachine028/memories/assets/93467074/2fb88a06-d4b6-4239-b82d-059a970096c3)

**Comment by VinayakVispute** [comment]
@warmachine028 Please Review my Issue

**Comment by VinayakVispute** [comment]
@warmachine028 Please Review my Issue

**Comment by VinayakVispute** [comment]
@warmachine028 Please Review my Issue

**Comment by VinayakVispute** [comment]
@warmachine028 I was busy yesterday. I wanna just let you know that i will make PR until tonight

**Comment by warmachine028** [comment]
Okay @VinayakVispute no problem
