### ISSUE TITLE
[DOCS 📄] Compact hacktoberfest banner for README.md

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#121]
### Description

- Right now the current hacktoberfest logo banner is very large and consuming a lot of space.
- Suggest a new compact logo that is similar to this original one in this README.md.

**Comment by adisuyash** [comment]
Hey I wwould like to work on this issue can this issue be assigned to me.
Thanks in advance for assigning me 😁

**Comment by adisuyash** [comment]
Will this image be fine in the README ?
![image](https://github.com/warmachine028/memories/assets/116362593/6292e199-056f-41de-a9ad-df59ea67b179)

**Comment by warmachine028** [comment]
Do you have any other images to choice from? One which only has the hacktoberfest written with the logo and 000010 below, like a Badge basically. Without the background.

I'm sure I saw something similar in another repository

**Comment by warmachine028** [comment]
Do you have any other images to choice from? One which only has the hacktoberfest written with the logo and 000010 below, like a Badge basically. Without the background.

I'm sure I saw something similar in another repository

**Comment by adisuyash** [comment]
Now I got your point,
Like just a header logo right?
Would a smaller logo be fine ?

**Comment by warmachine028** [comment]
You can show your Suggession

**Comment by adisuyash** [comment]
Here's what you're expecting for :
<img height="136" src="https://github.com/warmachine028/memories/assets/116362593/3f371181-b498-4442-84d0-38bc77c98064">

**Comment by warmachine028** [comment]
Yes this

**Comment by warmachine028** [comment]
Add this one

**Comment by adisuyash** [comment]
Is this issue not accepted in Hacktoberfest ?

**Comment by warmachine028** [comment]
Accepted
