### ISSUE TITLE
Hide unnecessary tabs or widgets

### ISSUE THREAD

**Issue by theritikchoure** [warmachine028/memories#18]
Hide below tabs - 

- Projects

Hide below widgets - 

- Releases 
- Packages

**Note -** Hide if you are not using

**Comment by warmachine028** [comment]
Can you elaborate?

**Comment by theritikchoure** [comment]
![image](https://user-images.githubusercontent.com/56495602/197245990-0c2a6c61-6617-48b6-b0f7-5e1b87d268a5.png)

You are not using ```projects``` tab, so you can disappear it.

---

![image](https://user-images.githubusercontent.com/56495602/197246169-bbeca587-bb4e-4e9e-aa27-3c86d6f931b2.png)

You are not using ```releases``` and ```packages``` widgets, so you can disappear them as well.

**Comment by warmachine028** [comment]
How to make them disapear? Can you do that for me?

**Comment by theritikchoure** [comment]
@warmachine028 

Only you can do that.

### For hiding the ```projects``` tab, follow these steps -

1. On GitHub.com, navigate to the main page of the repository.
2. Under your repository name, click  ```Settings ```.
3. Under ```Features```, unselect the ```Projects``` checkbox.

### For hiding the ```releases``` and ```packages``` tab, follow these steps -

1. On GitHub.com, navigate to the main page of the repository.
2. Click this 👇, gear icon near the about section
![image](https://user-images.githubusercontent.com/56495602/197320612-9943cfff-a7d1-42cc-873d-ea40e2d7f54a.png)

3. Go to ```Include in the home page``` section
4. Unselect the ```releases``` and ```packages``` checkboxes.

**Comment by warmachine028** [comment]
Alright i will be doing it asap. Closing this issue now.
