### ISSUE TITLE
(JS-0123) Local variable name shadows variable in outer scope

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#195]
## Description
Two variables can have the same name if they&#x27;re declared in different scopes. In the example below, the parameter `x` is said to &quot;shadow&quot; the variable `x` declared above it. The outer `x` can no longer be accessed inside the `sum` function.

## Occurrences
There are 10 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/warmachine028/memories:client/issue/JS-0123/occurrences/](https://app.deepsource.com/gh/warmachine028/memories:client/issue/JS-0123/occurrences/)

**Comment by Jai-Marothiya** [comment]
@warmachine028 - Please assign this issue to me. I can fix it.

**Comment by warmachine028** [comment]
Assigning you. Just to be clear, don't work on the main branch, that's depricated. Work on the *feature/new layout* branch

**Comment by DhruvGahoi** [comment]
@warmachine028 is this issue is not resolved yet?

**Comment by warmachine028** [comment]
Not resolved yet
