### ISSUE TITLE
Add Contributors Pannel.

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#22]
As this project is getting contributions, 
- I need a section at the bottom to show contributors icons
- Also add the contributors section reference in Table of Contents
- You might take reference from my UEMCRP project.

**Comment by Keerthivardhan1** [comment]
in which file you want to add contributors section in CONTRIBUTING.md  or README.md or in both

**Comment by warmachine028** [comment]
Only Below Readme.md

**Comment by Keerthivardhan1** [comment]
ok 
is heading name "Best Contributors" is ok or if not suggest one 
 as heading name in  readme.md file in UEMCRP project is same

**Comment by warmachine028** [comment]
Yes! It would be fine

**Comment by Keerthivardhan1** [comment]
ok I will do it

**Comment by Keerthivardhan1** [comment]
<img width="737" alt="done" src="https://user-images.githubusercontent.com/110013820/197346612-e1fa88f3-7446-4879-8ba2-9327ff854ced.png">
done bro

**Comment by warmachine028** [comment]
## Best Contributors 🎭
```
[![Best Contributors](https://contrib.rocks/image?repo=warmachine028/memories)](https://github.com/warmachine028/uemcrp/graphs/contributors)
```

**Comment by Keerthivardhan1** [comment]
bro  I registered for hacktoberfest 2022.
Can you tell me what type of prs they will accept.
Will documentation and small small changes in the code be accepted?

**Comment by Keerthivardhan1** [comment]
I am new to the git and github can i know 
is it ok if i raise pr for this issue as this is small ?
will this pr get accepted in hacktoberfest ?

**Comment by warmachine028** [comment]
It will get accepted. Just make a PR.

**Comment by warmachine028** [comment]
Please make sure to 🌟 this repo
