### ISSUE TITLE
[BUG-FIX] Fix code scanning alert - Hard-coded credentials

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#37]
### Description

Tracking issue for:
- [ ] https://github.com/warmachine028/memories/security/code-scanning/13
- Create an environment variable inside `server/.env.example`.
- Name: `TOKEN_SECRET`.
- Value: "Token Secret String"
- Replace the value of the variable `secret` in the file accordingly.
- Take help from other environment variables used for server for replacing the value.

### Screenshots

![image](https://user-images.githubusercontent.com/75939390/234909892-65320246-e6fa-4618-b0ec-6de2d4492c28.png)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by atharvarekhawar** [comment]
Your setup doc is not present

**Comment by atharvarekhawar** [comment]
I am new to open source contribution and want to start it with your issue , can you describe in detail the contribution process

**Comment by warmachine028** [comment]
> Your setup doc is not present

I have added the setup Guidelines

**Comment by warmachine028** [comment]
> I am new to open source contribution and want to start it with your issue , can you describe in detail the contribution process

Hi there,
Please read the Issue Description and let me know which part is confusing you, I will assist you to solve it.

**Comment by atharvarekhawar** [comment]
What I have understood from the above description is that the key is used as hard-coded text and I have to use an environment variable to hide the key, if mistaken please correct me.

**Comment by warmachine028** [comment]
Correct. You just have to replace the key using environment variable in the file and env.example

**Comment by atharvarekhawar** [comment]
sure I will do it, you can assign it to me and I have a doubt about a line in setup.md which is ->

Reset the index of the array from const API = axios.create({ baseURL: apiURL[1] }) to ...apiURL[0]... to reuse the deployed server

**Comment by atharvarekhawar** [comment]
One more doubt is that should I create a new branch in my fork or directly commit into main branch and what message should my commit contain after changes

**Comment by atharvarekhawar** [comment]
I was checking the folder structure and noticed .env.example file, do you want me to create a .env file  replacing it ?

**Comment by warmachine028** [comment]
> sure I will do it, you can assign it to me and I have a doubt about a line in setup.md which is ->
> 
> Reset the index of the array from const API = axios.create({ baseURL: apiURL[1] }) to ...apiURL[0]... to reuse the deployed server

Okay so this line indicates that:
- 0th item in the apiURL array is the deployed server
- 1st item is the Local server

If you have made changes in the server files and want to check if it is working fine, you might want to change `0` to `1`

But you need to reset it to `0` again before you push your changes

**Comment by warmachine028** [comment]
> I was checking the folder structure and noticed .env.example file, do you want me to create a .env file replacing it ?

- Yes the `.env` file and `.env.local` files are untracked by Git. 
- You might create it, but you might not be able to push it in the repository
- You can just make the changes in .env.example like the other variables present there.

**Comment by warmachine028** [comment]
> One more doubt is that should I create a new branch in my fork or directly commit into main branch and what message should my commit contain after changes

- As this is a minor change, creating a branch is upto you
- The commit message can be something like `fix: Added fixes for #37`

**Comment by atharvarekhawar** [comment]
I have changed the required code, please tell me if there is any procedure for creating a PR
