### ISSUE TITLE
[BUG FIX]: Missing Rate Limiting

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#39]
### Description

- Install **'express-rate-limit'** module
- Add a rate limiter in `./server/index.js`
- Rate Limiter is used to prevent DOS attacks.

Tracking issue for:
- [ ] https://github.com/warmachine028/memories/security/code-scanning/34
- [ ] https://github.com/warmachine028/memories/security/code-scanning/33
- [ ] https://github.com/warmachine028/memories/security/code-scanning/32
- [ ] https://github.com/warmachine028/memories/security/code-scanning/31
...
- [ ] https://github.com/warmachine028/memories/security/code-scanning/14

### Screenshots
Example:
![image](https://user-images.githubusercontent.com/75939390/235284309-8fafe31c-4ef4-4e70-bd6c-f06562a60de6.png)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by TheGuyD** [comment]
@warmachine028 can you assign me to solve this issue ?

**Comment by warmachine028** [comment]
Sure, assigning you

**Comment by warmachine028** [comment]
@TheGuyD How far is the work?

**Comment by TheGuyD** [comment]
@warmachine028 at the .env file there is a requirement for email ,password and a token . Which service do I sign in order to get that info? 

For the url I have MongoDB

**Comment by warmachine028** [comment]
You can refer to this [file](https://github.com/warmachine028/memories/blob/main/rules/ENV_VARIABLES.md). I have added the details after someone mentioned they are facing problems setting up environment variables.

**Comment by TheGuyD** [comment]
@warmachine028 done that , the output of npm start:

`file:///home/student/memories/server/middleware/auth.js:8
                const token = req.headers.authorization?.split(' ')[1];
                                                        ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)`

**Comment by warmachine028** [comment]
Try printing the secret variable, see if it is giving any output.

**Comment by TheGuyD** [comment]
@warmachine028 code is ready , now I'm testing it using goldeneye tool for ddos.

**Comment by TheGuyD** [comment]
@warmachine028  i'm gettin a 403 error when try to push

**Comment by warmachine028** [comment]
> @warmachine028  i'm getting a 403 error when try to push
> `remote: Permission to warmachine028/memories.git denied to TheGuyD.
> fatal: unable to access 'https://github.com/warmachine028/memories/': The requested URL returned error: 403`

- Actually you are trying to push in my Fork directly, which is not allowed 
- You should push in your fork, then create a PR.
- I will review the changes and accept the pull request.

**Comment by TheGuyD** [comment]
@warmachine028 thank you

**Comment by warmachine028** [comment]
If you liked working on this project, you can leave a star ⭐ to show appreciation.
