### ISSUE TITLE
[FEATURE] <Proper Doumentation for local setup>

### ISSUE THREAD

**Issue by Donbasilpeter** [warmachine028/memories#40]
### Description

A proper documentation for local setup will help in contribution. Details of env variables is not given on the rules.md. 
The following variables were confusing during first time setup of the local environment.

### Screenshots

![image](https://user-images.githubusercontent.com/48594177/235291980-e7c7b969-4a6e-477b-aca2-56b1e38ff45e.png)
![image](https://user-images.githubusercontent.com/48594177/235292003-f2ce81c1-f8e4-4918-aedd-218bf9e458c3.png)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
Sure, go for it. Assigning you

**Comment by Donbasilpeter** [comment]
Sorry, but I was confused with the tocken secret, and other variables. Thats why I raised this issue.

**Comment by Donbasilpeter** [comment]
It would be better if you assign it to some one already done the local setup.

**Comment by warmachine028** [comment]
Okay I will do it by myself then
