### ISSUE TITLE
[FEATURE] Theme toggle

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#43]
### Description

- Any modern web app these days support a light and dark themes, this website is no different
- We need a toggle switch to toggle between light and dark themes using CSS variables.
- Initially the value should be system default theme.
- Then the changed theme value must be stored in local storage.

### Screenshots

![download](https://user-images.githubusercontent.com/75939390/236682116-cbc1325a-89ff-4aeb-a8ec-32437cd0aebd.png)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by avinasdube** [comment]
Hey, I can do that. But, I'm having problem setting up the project locally on my machine. Can you please clarify steps to run the project on my machine locally ? Actually, I've never worked on MongoDB ever. So, it's my first time. I can also redesign the whole UI of  which I have an idea of.

**Comment by warmachine028** [comment]
> Can you please clarify steps to run the project on my machine locally ?

Sure, the steps for setting up the project is in [SETUP](https://github.com/warmachine028/memories/tree/main/rules). Let me know where you're facing any issue.

> Actually, I've never worked on MongoDB ever. So, it's my first time.

That won't be an issue right now because in this PR I just want a toggle switch similar to the one given above.

> I can also redesign the whole UI of which I have an idea of.

If you have any new design implementation for the theme switch suggest some below which would fit the existing UI.

**Comment by avinasdube** [comment]
Okay. I just got it running on my machine myself after some puzzling. Assign me the toggle issue. I'll do it and and make a PR when done. If there is any, you can let me know of time boundation. Thanks.

**Comment by avinasdube** [comment]
Toggle is done. But, I'd like to make few more changes to keep the look and feel of the UI relevant. Like in Dark mode the background image doesn't looks good enough. So, I want to remove to background image with a plain color palette. Do you approve it ? Also, some minor changes like some elements border radius, padding etc.

**Comment by warmachine028** [comment]
> But, I'd like to make few more changes to keep the look and feel of the UI relevant. Like in Dark mode the background image doesn't looks good enough. So, I want to remove to background image with a plain color palette.

Sure, but I would suggest to keep these 2 tasks in 2 seperate Issues. You can create a new issue to work on it after discussing on it. If you have made the toggle switch I would like to view it before you create a PR. Can you show the screenshots here?

**Comment by avinasdube** [comment]
Sure ! Here they are : 

On LightMode :

![LightMode](https://github.com/warmachine028/memories/assets/85872996/f0a58e48-dd47-4d0f-895c-d9844e7bc8cc)

On DarkMode :

![DarkMode](https://github.com/warmachine028/memories/assets/85872996/3a8ff4e1-6639-4dd8-bfc8-0eaa36f6b9a6)

The toggle button is based on React States. Easy to implement in any component and page. React Context API has been used to make it available everywhere. Suggest if changes needed.

**Comment by warmachine028** [comment]
This looks good but what happened to the font? The font was not like this before. It was simple

**Comment by avinasdube** [comment]
> This looks good but what happened to the font? The font was not like this before. It was simple 

I have not changed any font or font related setting. It is running from your remote server, so maybe it's unable to access the real font that you have already set up. Maybe, it's not available offline on my machine. The font settings are default.

**Comment by warmachine028** [comment]
Sure, please make the PR. Any changes will be suggested after viewing on the preview generated by vercel

**Comment by avinasdube** [comment]
I have made the PR. But, it is not generating preview even there is no merge conflict.

**Comment by warmachine028** [comment]
Sure! I have requested some changes
