### ISSUE TITLE
[FEATURE] Animation in Theme toggle Button

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#52]
### Description

- The theme toggle button in the application is currently generic and needs to be customized.
- It is requested to add a subtle animation that transitions from day to night when toggling the theme.
- The animation should provide a visually pleasing effect that enhances the user experience.
- The animation should be smooth and seamless, ensuring a gradual change in the appearance of the toggle button.
- The design and duration of the animation can be discussed and finalized in collaboration 

### Screenshots

- Something with a similar animation is expected
![Day-Night-Toggle-with-Background-Animation](https://github.com/warmachine028/memories/assets/75939390/ece43c33-2c4d-4777-914e-445bc67866de)

### Additional information

- The animation can be implemented using CSS transitions, animations.

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by PratikMbade** [comment]
@warmachine028  assign me , i want to work on this issue.

**Comment by warmachine028** [comment]
You have already been assigned to one issue, once you complete it. I can assign you in this issue if someone doesn't ask first.

**Comment by avinasdube** [comment]
Assign me !

**Comment by warmachine028** [comment]
> Assign me !

Yes, I believe you are the perfect person to work on this, since you have done such a great work implementing the whole dark theme by yourself. 

Just make sure to update your branch with the latest changes

**Comment by avinasdube** [comment]
Okay ! Thank You 🙏

**Comment by avinasdube** [comment]
Sorry for this much time. I had to travel somewhere suddenly so it took me some time. It's ready now, I'll be making the PR soon.
