### ISSUE TITLE
[FEATURE] Add name in PublicProfile

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#54]
### Description

- The name of a user would be a good addition in the public profile
- The attributes are already available from server.
- It needs to be presented correctly like the other attributes.

## Important:

- The name attribute must only be present in the PublicProfile component. Hence the UserDetails Component should be left untouched.

### Screenshots

![Screenshot 2023-07-16 153741](https://github.com/warmachine028/memories/assets/75939390/04199522-3e29-47cb-a437-aa5faaa39ea4)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by PratikMbade** [comment]
assign me , i want to work on this issue

**Comment by warmachine028** [comment]
Sure assigning you.

**Comment by warmachine028** [comment]
Just make sure not to change anything in the UserDetails component. Both the compoents are exported from the same file

**Comment by PratikMbade** [comment]
@warmachine028 Okay.

**Comment by warmachine028** [comment]
@PratikMbade What's the status of the work?

**Comment by warmachine028** [comment]
Fixed by 42ffe1e
