### ISSUE TITLE
Mobile Responsiveness Issue

### ISSUE THREAD

**Issue by 0rigin-c0de** [warmachine028/memories#59]
**Describe the bug**
When I see this beautiful website on a mobile device at 360px to read the whole post created by users I saw an insane thing the Post title is very big and looked very ugly and bad user experience

**To Reproduce**
1. Go to Mobile Screen 
2. Click on any post
3. Scroll down to the post title
4. See the error

**Expected behavior**
The title's font size should be small on mobile screens it looks awesome

**Screenshots**
![Screenshot 2023-07-26 134821](https://github.com/warmachine028/memories/assets/106311923/b9a15b0e-20f1-4161-93fc-de014e31809f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version 11

**Smartphone (please complete the following information):**
 - Device: Redmi 9 Prime
 - OS: Android
 - Browser Brave
 - Version 12

**Additional context**

**Comment by 0rigin-c0de** [comment]
Kindly assign it to me @warmachine028

**Comment by warmachine028** [comment]
Yes get assigned and fix this issue.

**Comment by 0rigin-c0de** [comment]
I also want to style scrollbar
