### ISSUE TITLE
[FEATURE] Custom Scrollbar Styling

### ISSUE THREAD

**Issue by 0rigin-c0de** [warmachine028/memories#61]
### Description

 My suggestion is to implement custom scrollbar styling to complement the overall design and aesthetics. As we know, a visually appealing interface contributes significantly to user engagement and satisfaction.
As a user of Memories, I believe that these custom scrollbar styles would elevate the overall user experience and align better with the website's design vision.

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by 0rigin-c0de** [comment]
Assign it to me @warmachine028

**Comment by warmachine028** [comment]
Assigned

**Comment by warmachine028** [comment]
What's the status of work?

**Comment by 0rigin-c0de** [comment]
apologies, I will make changes soon

**Comment by 0rigin-c0de** [comment]
@warmachine028 take a look on this bro

**Comment by 0rigin-c0de** [comment]
thanks @warmachine028 bro

**Comment by warmachine028** [comment]
@0rigin-c0de make sure to star this project if you liked contributing to it
