### ISSUE TITLE
[BUG 🐞] Fix code scanning alert - Change user-controlled sources for GoogleSignIn

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#70]
### Description

- Location: [`server/controllers/user`](https://github.com/warmachine028/memories/blob/main/server/controller/user.js)
- If a database query (such as a SQL or NoSQL query) is built from user-provided data without sufficient sanitization, a malicious user may be able to run malicious database queries.
- Perform the following change

## Tracking issue for:
- [ ] https://github.com/warmachine028/memories/security/code-scanning/2

### Screenshots

Before:
```js
export const googleSignin = async (req, res) => {
	const { name, email, image, googleId } = req.body

	try {
		const id = new mongoose.Types.ObjectId(googleId)
		const user = await User.findByIdAndUpdate(id, { name, email, image }, { upsert: true })
                ...
```

After:
```js
export const googleSignin = async (req, res) => {
	const { name, email, image, googleId } = req.body


	try {
		if (![name, email, image].every((field) => typeof field === "string")) {
			return res.status(400).json({ status: "error" });
		}
		const user = await User.findByIdAndUpdate(googleId, { name, email, image }, { upsert: true })
```

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by vibh1103** [comment]
Hi @warmachine028 can i pick this issue ?

**Comment by warmachine028** [comment]
Sure, I'm assigning you

**Comment by vibh1103** [comment]
Hi @warmachine028 
https://github.com/warmachine028/memories/commit/7e348c0d8655deb1ade828a28fc6a4fe40e9d7c5
This change is made in this commit can you confirm me once what i have to do ?

**Comment by warmachine028** [comment]
Seems like this Issue was already fixed by the Commit, wait I am creating another similar issue for another vulnerability, you can fix that.

**Comment by warmachine028** [comment]
@vibh1103 please see #85
