### ISSUE TITLE
[FEATURE 💡] Migrate to Vite

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#72]
### Description

- As CRA was [deprecated](https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o#:~:text=React%20developer%20team%20recently%20removed,react%2Dapp%20is%20finally%20gone.) long ago, it is not recommend to use in a repo like this.
- Planning to Migrate from CRA to vite
- Heres a [Blog Post](https://dev.to/henriquejensen/migrating-from-create-react-app-to-vite-a-quick-and-easy-guide-5e72) for quick and easy migration.
- Here's another [one](https://www.asserts.ai/blog/migrataion-react-cra-vitejs)

### Screenshots

![download.png](https://github.com/warmachine028/memories/assets/75939390/2fbad507-0cc9-4fa2-8b5e-9d83794d97fe)

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by cyblogerz** [comment]
Hey can you assign this to me ?

**Comment by warmachine028** [comment]
Sure

**Comment by cyblogerz** [comment]
<img width="667" alt="image" src="https://github.com/warmachine028/memories/assets/74711322/1149dac3-31bf-476a-8860-03c9047e94aa">

Getting error while migrating, as ChipInput.js uses commonjs

**Comment by warmachine028** [comment]
were you able to resolve it somehow?

**Comment by cyblogerz** [comment]
I tried to resolve it, but It was getting complicated as the ChipInput file has about 1000 lines of code. I tried to use other libraries, but it did not end well :(

**Comment by warmachine028** [comment]
For now I would suggest do one thing, comment out the use of that component but don't delete it. And create a PR.

**Comment by cyblogerz** [comment]
Will do that then
