### ISSUE TITLE
[BUG 🐞] Post Updates Doesn't clear form data

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#73]
### Description

- Post Updates keep form Data as Usual after updating.
- The clear Callback method must be invoked
- This callback method is passed with the update post dispatch event

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Vayras** [comment]
hi @warmachine028  I would like to contribute towards this issue , I have setup the project on local machine , can you tell me how to replicate this issue?

**Comment by warmachine028** [comment]
Sure, 
- When we update a post from the Form component, 
- After updation the form must get cleared, but it is not.
- The clear callback is passed to the dispatch, but has not been accepted and called inside `updatePost` method inside `actions/posts.js`

**Comment by warmachine028** [comment]
Sure, 
- When we update a post from the Form component, 
- After updation the form must get cleared, but it is not.
- The clear callback is passed to the dispatch, but has not been accepted and called inside `updatePost` method inside `actions/posts.js`

**Comment by warmachine028** [comment]
@Vayras, assigning you

**Comment by warmachine028** [comment]
@Vayras what's the status? Will you be able to solve it?

**Comment by ansh-kaushik** [comment]
@warmachine028  is the issue still open

**Comment by warmachine028** [comment]
Yes it is open, would you like to get assigned?

**Comment by warmachine028** [comment]
Yes it is open, would you like to get assigned?

**Comment by abdulrehmanjaved-1** [comment]
Hey Warmachine!
Assign this issue to me, I'll solve it tomorrow.
Thanks

**Comment by warmachine028** [comment]
Assigned

**Comment by abdulrehmanjaved-1** [comment]
Thanks

**Comment by warmachine028** [comment]
> Thanks

What's the status of work?

**Comment by abdulrehmanjaved-1** [comment]
Going to start now

**Comment by abdulrehmanjaved-1** [comment]
Hey do you want to clear the form after user updates his/her post?.

**Comment by warmachine028** [comment]
@abdulrehmanjaved-1 read above conversation

**Comment by abdulrehmanjaved-1** [comment]
Got it
