### ISSUE TITLE
[BUG 🐞] Warnings in console

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#76]
### Description

- Upon updating the deps of this project to migrate from react 17 to latest react 18 along with Vite 
- App has been generating this warning message given below.
- Please take necessary actions to remove this warning.

### Screenshots

![image](https://github.com/warmachine028/memories/assets/75939390/68ce3d49-fa00-4f3c-99a9-f244f2a268c2)

### Additional information

- This warning is visible only when we run the app locally using `npm run dev`.
- Only push updates to **[deps-update](https://github.com/warmachine028/memories/blob/deps-update)** not **main** branch.
- Preview the latest deploy **[here](https://memories-latest.vercel.app)**.

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Priyankaa2503** [comment]
Hi, i would like to contribute to this issue as a part of Hacktoberfest.

**Comment by warmachine028** [comment]
Assigning you, please work on it

**Comment by warmachine028** [comment]
Please fork the deps-update branch

**Comment by warmachine028** [comment]
@Priyankaa2503 Have you been able to progress in this?

**Comment by Priyankaa2503** [comment]
Hi, i have raised a PR for this issue. Please do let me know if any further changes are required.
