### ISSUE TITLE
[BUG 🐞] Outlines are not visible in dark mode

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#79]
### Description

- The form outlines are not visible in dark mode for SignIn and SignUp forms
- Do not change anything for Default mode, only change it for Dark (Light)
- You can take reference from the Form.jsx component styles.

### Screenshots

![Screenshot_2023-10-02-20-50-33-091_com android chrome](https://github.com/warmachine028/memories/assets/75939390/1bcdf7a5-8b24-40f3-827d-6f91b538f981)

- Supposed to look similar to this 
![Screenshot_2023-10-02-21-03-29-175_com android chrome](https://github.com/warmachine028/memories/assets/75939390/e9c1136e-295c-4b8f-85df-16e605c44b97)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by RacHiT101** [comment]
hey @warmachine028 can u  assign this to me ?

**Comment by warmachine028** [comment]
Sure assigning you

**Comment by a-s-t-e-y-a** [comment]
Hi @warmachine028,

I've generated a PR to address the issue at hand. You can find it [here](https://github.com/warmachine028/memories/pull/81).

Please review the changes made in the PR, and if it aligns with your requirements, kindly consider merging it. If there are any reasons for not merging it, please provide feedback so that I can make the necessary adjustments.

Thank you for your time and attention to this matter.

Best regards,
krishna seth

**Comment by warmachine028** [comment]
> Hi @warmachine028,
> 
> I've generated a PR to address the issue at hand. You can find it [here](https://github.com/warmachine028/memories/pull/81).
> 
> Please review the changes made in the PR, and if it aligns with your requirements, kindly consider merging it. If there are any reasons for not merging it, please provide feedback so that I can make the necessary adjustments.
> 
> Thank you for your time and attention to this matter.
> 
> Best regards, krishna seth

- You must have gotten assigned to this issue before proceeding, someone was already working on it.
- I won't close your PR right now, since I know you have put efforts.
- I would wait for @RacHiT101 till tomorrow, if he is unable to solve it by then, I will assign you to it.
- Then I will review and request necessary changes if needed.
- Add hacktoberfest-accepted tags and merge the PR.

**Comment by warmachine028** [comment]
@a-s-t-e-y-a I have assigned you to this issue

**Comment by a-s-t-e-y-a** [comment]
@warmachine028 Thanks 
I'll make the changes you asked

**Comment by a-s-t-e-y-a** [comment]
@warmachine028 I fix the issue that you stated 
Kindly review the PR
