### ISSUE TITLE
[BUG 🐞] Fix code scanning alert - Change user-controlled sources for getUser

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#85]
### Description

- Location: [`server/controllers/user`](https://github.com/warmachine028/memories/blob/main/server/controller/user.js)
- If a database query (such as a SQL or NoSQL query) is built from user-provided data without sufficient sanitization, a malicious user may be able to run malicious database queries.
- Perform the following change

Tracking issue for:
 https://github.com/warmachine028/memories/security/code-scanning/40

### Screenshots

Before:

```js
export const getUser = async (id) => {
	try {
		const userId = id
		const user = await User.findById(userId)
                ...
```

After:

- Please refer to #70 for hints 

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by nikolai1312** [comment]
Hey, i would like to help on this issue!

**Comment by warmachine028** [comment]
Assigned

**Comment by warmachine028** [comment]
@nikolai1312 what is the progress?

**Comment by nikolai1312** [comment]
@warmachine028 Right now i'm at my job, soon as i stop working i'll start on this issue and report here the progress.

**Comment by warmachine028** [comment]
> @warmachine028 Right now i'm at my job, soon as i stop working i'll start on this issue and report here the progress.

Alright take your time.

**Comment by nikolai1312** [comment]
Starting to work on this issue right now, making the setup on my computer.

**Comment by nikolai1312** [comment]
Didn't have much time yesterday, but already making code progress today, i guess that until sunday i'll commit the changes.

**Comment by warmachine028** [comment]
What's the status? @nikolai1312

**Comment by nikolai1312** [comment]
@warmachine028 had some issues while setting up the enviroment, but i got an idea for this issue, look in this commit [34fad60](https://github.com/nikolai1312/memories/commit/34fad60319c325d8b49488fcad958238e5d71d71), i just converted the input into a ObjectId type from mongoDB and passed into the userID variable, then i added a conditional statement to check if the type is really a ObjectId, otherwise it'll throw an exception. What do you think?

**Comment by nikolai1312** [comment]
> @warmachine028 had some issues while setting up the enviroment, but i got an idea for this issue, look in this commit [34fad60](https://github.com/nikolai1312/memories/commit/34fad60319c325d8b49488fcad958238e5d71d71), i just converted the input into a ObjectId type from mongoDB and passed into the userID variable, then i added a conditional statement to check if the type is really a ObjectId, otherwise it'll throw an exception. What do you think?

Also, i didn't find where this method is being called, so didn't know how to test if it works properly.

**Comment by warmachine028** [comment]
I believe you can just add a conditional check before executing the query to know if the userId passed is a string or not like issue #70

**Comment by warmachine028** [comment]
> > @warmachine028 had some issues while setting up the enviroment, but i got an idea for this issue, look in this commit [34fad60](https://github.com/nikolai1312/memories/commit/34fad60319c325d8b49488fcad958238e5d71d71), i just converted the input into a ObjectId type from mongoDB and passed into the userID variable, then i added a conditional statement to check if the type is really a ObjectId, otherwise it'll throw an exception. What do you think?
> 
> Also, i didn't find where this method is being called, so didn't know how to test if it works properly.

[Here](https://github.com/warmachine028/memories/blob/main/server/controllers/user.js)

**Comment by nikolai1312** [comment]
> I believe you can just add a conditional check before executing the query to know if the userId passed is a string or not like issue #70

Sure, will implement that way then, just tought that this approach would be better to check strictly the data type. I'm going to commit with this change you suggested.
