### ISSUE TITLE
[DOCS 📄] Demo Section

### ISSUE THREAD

**Issue by rasvanjaya21** [warmachine028/memories#86]
### Description

Issued : the demo section of latest version of this repository doesn't show the gif.

**Comment by warmachine028** [comment]
- Can you create a short demo gif under 20 mb to upload it to the README so that it displays properly.
- You can download the gif locally to view it to take ideas

**Comment by rasvanjaya21** [comment]
Wait, I have already fixed the gif issue from gif obtained from the [memories-old](https://github.com/warmachine028/memories/tree/memories-old) branch. Wait my PR and, so assign me sir.

**Comment by warmachine028** [comment]
memories-old has the older UI, the new UI has more changes added to it,

**Comment by rasvanjaya21** [comment]
Okay sir, I will record the new UI gif under 20 MB as you mention it before, wait.

**Comment by warmachine028** [comment]
I have a software to help you with that

**Comment by warmachine028** [comment]
I have a software to help you with that

**Comment by warmachine028** [comment]
https://github.com/NickeManarin/ScreenToGif

This

**Comment by rasvanjaya21** [comment]
Yes, we are one mind, I thought that also, I already typed Scree........ in half way kwkwk. Thank you
