### ISSUE TITLE
[FEATURE 💡] Dark mode for ForgotPassword

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#87]
### Description

- Forgot password form does not have proper dark mode like other forms
- [See this page](https://memories-pritam.vercel.app/auth/forgotPassword) 

### Screenshots

![image](https://github.com/warmachine028/memories/assets/75939390/9f5d90c9-8c04-4c43-a5fd-8f13ab8c8a30)

- Normal Form component

![image](https://github.com/warmachine028/memories/assets/75939390/c90be805-67ea-419b-a430-080acadc7af6)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by shaheedhudheen** [comment]
I would like to contribute to this project by working on this issue.

**Comment by warmachine028** [comment]
Recently someone fixed #79 you can take reference from their PR too.

**Comment by shaheedhudheen** [comment]
> Recently someone fixed #79 you can take reference from their PR too.

Ok

**Comment by warmachine028** [comment]
Have you made any progress in this issue?

**Comment by amitgiri72** [comment]
I would like to contribute to this feature ,Please assigned this to me
