### ISSUE TITLE
[BUG 🐞] Page Crashes!

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/memories#89]
### Description

- Page Crashes on going to User Details
- Also while comming back from PostDetails
- Identify the Bug and Resolve it ASAP
- Could be due to migration from react.v17 to react.v18

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by cheesequake** [comment]
Hey! I would like to contribute to this issue

**Comment by warmachine028** [comment]
sure, you can work on it, assigning you.

**Comment by warmachine028** [comment]
@cheesequake were you able to progress with it?

**Comment by cheesequake** [comment]
@warmachine028 unfortunately I am unable to figure this out 😞

**Comment by warmachine028** [comment]
@cheesequake it's fine at least your tried, maybe you learnt something. I'll assign someone else to it or I'll solve it by myself

**Comment by mehulrnsit** [comment]
Hey @warmachine028 I would like to take up this issue

**Comment by warmachine028** [comment]
@mehulrnsit assigning you

**Comment by ddas2707** [comment]
Hey @warmachine028 I would like to contribute to this issue

**Comment by warmachine028** [comment]
@ddas2707 someone is already assigned to it, if @mehulrnsit is unable to solve you can work on it

**Comment by cesardlinx** [comment]
I also offer to help with this problem if everyone else couldn't solve it 🙂

**Comment by warmachine028** [comment]
Start solving it, make a PR asap, keeping this open to all

**Comment by cesardlinx** [comment]
Ok @warmachine028 there it is the fix

**Comment by mehulrnsit** [comment]
Hi @warmachine028, sry had a long day at the office yesterday, the issue was with one of the imports and I think @cesardlinx has already fixed it so you can assign this to him :)

**Comment by cesardlinx** [comment]
No worries @warmachine028 we understand, thank you man appreciate it 👍
