### ISSUE TITLE
[BUG 🐞] Duplicate module imports found

### ISSUE THREAD

**Issue by beneyalraj** [warmachine028/memories#91]
### Description

Anti-pattern
Found duplicate imports on 4 files 

### Screenshots

<img width="789" alt="Screenshot 2023-10-03 at 3 01 25 PM" src="https://github.com/warmachine028/memories/assets/42829681/cc561b0b-e769-44b4-89fd-9068b95afa39">
<img width="784" alt="Screenshot 2023-10-03 at 3 01 34 PM" src="https://github.com/warmachine028/memories/assets/42829681/1f6c619c-f600-456f-9be6-1b872418eda9">
<img width="785" alt="Screenshot 2023-10-03 at 3 01 43 PM" src="https://github.com/warmachine028/memories/assets/42829681/e63d1e29-cb91-4183-a19a-0bf8b0402c9b">

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
Assigning you
