### ISSUE TITLE
[BUG 🐞] Found unused variables, state and function

### ISSUE THREAD

**Issue by beneyalraj** [warmachine028/memories#92]
### Description

found unused variables, state and functions in 3 files 

### Screenshots

<img width="784" alt="Screenshot 2023-10-03 at 6 38 58 PM" src="https://github.com/warmachine028/memories/assets/42829681/32453659-587f-4f3d-bd3e-55e75c1d272f">
<img width="784" alt="Screenshot 2023-10-03 at 6 37 13 PM" src="https://github.com/warmachine028/memories/assets/42829681/4e9befac-bfee-4601-b270-3d8c0d110aa0">
<img width="786" alt="Screenshot 2023-10-03 at 6 38 38 PM" src="https://github.com/warmachine028/memories/assets/42829681/a23a7d8b-074b-447b-992a-80f04d34b462">

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
These are dependent on chipInput.js being temporarily solved by #82. So I have to close this issue for now
