### ISSUE TITLE
[BUG 🐞] Tags Input field size incorrect when empty

### ISSUE THREAD

**Issue by Faisalhs51** [warmachine028/memories#97]
### Description

The tags input field is in incorrect size when empty.

### Screenshots

![image](https://github.com/warmachine028/memories/assets/89152237/fc29ac1b-1bb5-4133-99f2-c73d505c3d0d)

### Additional information

- Always use styled components instead of plain CSS and MUI components.
## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by Faisalhs51** [comment]
@warmachine028 assign me this, I will resolve it

**Comment by warmachine028** [comment]
Assigning you
